apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-workflows-config-map
  labels:
    workflows.argoproj.io/configmap-type: Parameter
  annotations:
    workflows.argoproj.io/default-artifact-repository: gcs-artifact-repository
data:
  registry: location/project
  super-resolution-bucket: project_sr-shared
  private-bucket: project_meoss
  gcs-artifact-repository: |
    gcs:
      bucket: project_meoss
      serviceAccountKeySecret:
        name: gcs-credentials
        key: serviceAccountKey
