import os
import argparse
import logging


def waterSurf_Mask(src: str, dst: str) -> None:
    """
    :param src: The source image path.
    :param dst: The destination path where the mask will be saved.
    :return: None

    This method generates a water surface mask for a given image file.
    The mask is generated by applying a mathematical expression
    The expression used is "1*(A<0)", where `A` represents the input image.

    Example usage:
        src = "/tmp/NDPI_20210115_T31TCJ.tif"
        dst = "/home/WaterSurf_mask_20210115_T31TCJ.tif"
        waterSurf_Mask(src, dst)
    """
    expr = '\"1*(A<0)\"'
    cmd_mask = "gdal_calc.py -A " + src + " --type=Byte --outfile=" + dst + " --calc=" + expr
    os.system(cmd_mask)
    return
    

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--src', help='Source image path.')
    parser.add_argument('--dst', help='Destination image path')

    logging.basicConfig(
        format='%(asctime)s %(levelname)-8s %(message)s',
        level=logging.INFO,
        datefmt='%Y-%m-%d %H:%M:%S')

    logging.info('sub-process started.')
    args = parser.parse_args()
    waterSurf_Mask(args.src, args.dst)
